### ISSUE TITLE
Missing Variables

### ISSUE THREAD

**Issue by Paul-Ndirangu** [Jayem-11/sign_language_detection#1]
## This is a great project. 

I have identified a minor issue: You left our two keys and their respective variables in the dictionary "**_labels_dict_**"
The two are: 
-  "J"
- "Z"

**Comment by Jayem-11** [comment]
Thank you.

I Left out both J and Z since, they both require motion to be represented. Unlike the rest of the alphabet whereby you could do object detection on the frames, letter J and Z would require action recognition.

**Comment by Paul-Ndirangu** [comment]
Thank you for your reply

I appreciate your feedback

Best, regards,

Paul Ndirangu
+254725208403
https://www.linkedin.com/in/paul-ndirangu/
Data Scientist
